### ISSUE TITLE
Caller is incorrect when using level filter after adding the default caller

### ISSUE THREAD

**Issue by nboukeffa** [go-kit/kit#1086]
Hi, it seems that when we set the filter after adding the DefaultCaller the caller value is not correct anymore. Is that intended? 

```golang
	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
	logger = log.With(logger, "ts", log.DefaultTimestampUTC, "caller", log.DefaultCaller)
	logger = level.NewFilter(logger, level.AllowError())
	level.Error(logger).Log("msg", "an error message")

```

> output:  ts=2021-04-30T11:32:09.435Z **_caller=level.go:63_** level=error msg="an error message"

```golang
	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
	logger = level.NewFilter(logger, level.AllowError())
	logger = log.With(logger, "ts", log.DefaultTimestampUTC, "caller", log.DefaultCaller)
	level.Error(logger).Log("msg", "an error message")
```

> output level=error ts=2021-04-30T11:34:28.446655Z **_caller=main.go:14_** msg="an error message"

**Comment by ChrisHines** [comment]
It isn't intended so much as unavoidable. It is a consequence of how the Go standard library provides stack information and the way stack frames build up.

When requesting stack information we have to specify how many stack frames to skip from the current frame to get to the one we are interested in. `log.DefaultCaller` skips three frames because that works correctly as long as the logger is only wrapped by more calls to `log.With` and it's siblings. The `log.With` functions use an internal trick to prevent more stack frames from accumulating each time you use it. But log wrappers from other packages (like `level.NewFilter`) cannot cooperate in that scheme, so they add extra frames to the call stack seen when the `Log` method is called.

The workaround (if you need it) is to use [`log.Caller(depth int)`](https://pkg.go.dev/github.com/go-kit/kit/log#Caller) with the `depth` parameter that works for your configuration instead of `log.DefaultCaller` (which is defined as [`DefaultCaller = Caller(3)`](https://pkg.go.dev/github.com/go-kit/kit/log#pkg-variables))

Hope that helps.
