### ISSUE TITLE
How do I use service discovery with kubernetes and how do I deploy to kubernetes?

### ISSUE THREAD

**Issue by LeKDTrey5** [go-kit/kit#1087]

**Comment by sagikazarmark** [comment]
Kubernetes provides DNS based service discovery which means you could use the DNS SRV implementation, but since it's DNS based, you can just use DNS names to connect to your services, you don't really need the service discovery layer of Go kit.

As for deploying to Kubernetes: you have a plethora of options. :) I'd suggest looking at Helm or Kustomize.

Here is a go-kit based application, deployed with Helm: https://github.com/sagikazarmark/modern-go-application
