### ISSUE TITLE
package metrics/influx

### ISSUE THREAD

**Issue by zapient** [go-kit/kit#215]
Although you could get by with StastD it would be nice to have native InfluxDB metrics reporting

**Comment by peterbourgon** [comment]
As far as I'm aware, there is no such thing as native InfluxDB metrics reporting, because Influx has no first-order concept of metrics: it's just a plain TSDB. You would need to treat it similar to the current metrics/expvar package, i.e. couple it with a metrics/statistical intermediary like codahale/metrics. If you go to the Slack channel and look at the history you'll see that @dschalla is working on doing something like this. I'm not sure how far along he is.

**Comment by DSchalla** [comment]
I planned to work on it this weekend, sadly had to postpone it. Right now counter value get reported in a defined interval to influxdb, todo are gauge and histogram and tests for all of these. I expect to open a PR for comments somewhere in the upcoming week.

**Comment by peterbourgon** [comment]
#265
