### ISSUE TITLE
Add semver tags to this repo

### ISSUE THREAD

**Issue by dskarataev** [go-kit/kit#279]
Hi, we use your library in production, and we wanna have flexibility in updating to new *minor* versions automatically using "glide up" command. But in this repo it's not clear where is new minor and where is new major (incompatible) version of the code, so now we have to guess which commit is a new major version, that is very inconvenient.

Please add these tags on usual basis and also fill these tags for already commited code. Thanks.

http://semver.org/

**Comment by peterbourgon** [comment]
Thanks for raising the issue. I've resisted doing this so far, because I wanted to make sure Go kit could move, and change, as quickly as possible as we iterated to reach coherent and stable APIs. But I think a year+ is enough runway :)

I'll tag the ~current state as a 0.1.0 in the next day or two. Then, I suggest we keep it as lightweight as possible. I'll tag a new minor release once master collects a few new features, with a max timeout of (let's say) 1 month, modulo code churn. Patch releases for bugfixes (natch) but I'm going to resist backporting bugfixes to previous releases, at least for the time being. And we can target a 1.0 by end-of-year.

Thoughts?

**Comment by dskarataev** [comment]
Hi, thanks for your answer.

What is important for us is not to break our project's functionality because of dependencies update. We want to specify some version like 1.* and all next commits with tags starting from 1 should not contain any breaking change. So we can have the flexibility to update the dependency but we have a safety at the same time.

I hope it's possible :)

**Comment by peterbourgon** [comment]
I will still add semver as I mentioned above, but I would caution you that specifying a dep version with wildcards (e.g. 0.1.*) or "at least" carat notation (e.g. 0.1.1^) is generally bad practice. People make mistakes; there are no guarantees that a dependency won't ship breaking changes with a patch-level release. 

Unless you have a really good reason to do otherwise, you should really specify precise dependency versions (e.g. 0.1.2) and always fully test changes before shipping them — for Go kit, and all other deps in your glide file.

**Comment by dskarataev** [comment]
Thanks, but for dependencies freezing we use glide.lock

glide.yaml + glide up for version flexibility
glide.lock for safety

and basic workflow is:
1. glide up
2. check is everything ok
3. commit glide.lock

So the current problem now that if semver is not used, on step 2 we usually get something uncompatible. If it will be because of human error **sometimes** it's ok and it will not break our project. But when it's every time that is not so good :)

**Comment by peterbourgon** [comment]
https://github.com/go-kit/kit/releases/tag/v0.1.0 :tada:

**Comment by sevein** [comment]
Congrats!
