### ISSUE TITLE
Revel (considered harmful)

### ISSUE THREAD

**Issue by fluxibox** [go-kit/kit#350]
Hi go-kit,

You write Revel is considered harmful. Why?

Kind Regards,
Martin

**Comment by peterbourgon** [comment]
Revel relies heavily on a particular form of dependency injection and inversion-of-control, which make Revel applications nonidiomatic in the Go ecosystem, and difficult to reason about. In my opinion, Revel explicitly rejects what makes Go great, and cargo-cults practices from other language ecosystems (namely Ruby) which are nonsensical in, and even antithetical to, Go.

**Comment by AdamJacobMuller** [comment]
While I am not trying to argue against this, I think the current notation on the readme.md is not useful, merely for not being in-depth enough.

This issue is the top result for me on google for "revel considered harmful". I would personally appreciate a more in-depth explanation of what you mean by that? Perhaps there is some other information elsewhere I can reference or you could expound upon it here. Could we then link the considered harmful text somewhere even just this issue, or a better resource.

**Comment by peterbourgon** [comment]
I added a link to this issue.
