### ISSUE TITLE
metrics: add support for PCP

### ISSUE THREAD

**Issue by suyash** [go-kit/kit#354]
I was [a part of this year's Google Summer of Code](https://summerofcode.withgoogle.com/projects/#6178186094182400) with the [Performance Co-Pilot organization](http://pcp.io/). PCP, although principally built for reporting low level application specific metrics, also supports instrumentation through a specially configured agent, mmv. My project was to build an instrumentation client library for that API, and it is currently at [performancecopilot/speed](https://github.com/performancecopilot/speed).

One of the goals of the project was to demonstrate real world usage of the implemented client library, and I am trying to fulfill that requirement by implementing PCP support for this library. My fork contains a pcp subpackage inside metrics at https://github.com/suyash/kit.

I have also modified 3 examples to report metrics to PCP instead of prometheus and they are implemented [in a separate tree](https://github.com/suyash/kit/tree/pcp-examples/examples). For stringsvc2, I have added [some screenshots](https://github.com/suyash/kit/tree/pcp-examples/examples/stringsvc2#stringsvc2).

Currently I cannot support `With` labels for metrics, because while we do have a similar concept (https://github.com/performancecopilot/speed#instancemetric), it requires all labels to be specified upfront, and reinitializing a new metric each time seemed overkill. Instead I am [trying to explore supporting mutating instances](https://github.com/performancecopilot/speed/issues/32)

Anyways, in line with the contributing guidelines, I am opening this issue for discussion

**Comment by peterbourgon** [comment]
Neat! I'll take a look in the next few days.

> Currently I cannot support With labels for metrics, because while we do have a similar concept (https://github.com/performancecopilot/speed#instancemetric), it requires all labels to be specified upfront,

This is also true of Prometheus! Just make sure the With invocations are storing the label-values in a way that's retrievable by the observe method, and have the observe method pass the values to the underlying implementation. You can be permissive, and say that required unspecified dimensions get an "unknown" value, and non-required erroneously-specified dimensions are ignored. Or, you can be super strict, and panic on either condition. Either one is fine from my POV.

**Comment by peterbourgon** [comment]
Global state is always a bad idea, and in Go kit it's strictly forbidden. So you'll need to find a way to arrange things so that you don't have a package global registry and client. I haven't dug too deeply, but one way might be by encapsulating them in a pcp.Reporter struct, and have the NewMetric constructors be methods on that type.

**Comment by peterbourgon** [comment]
Great! The design of the new package looks reasonable from a high level.

But—I'd like to have a conversation with you about the design of PCP before I get into more details of what Go kit integration would look like. Something lower-latency than GitHub issues would be ideal: are you on the Gophers Slack? We can also have it here if that's easier for you.

**Comment by suyash** [comment]
@peterbourgon I have joined the slack channel

To give a general overview of the design, PCP is a low level system monitoring toolkit, the individual systems are monitored through system specific agents, which are programmed in a manner in which they know what to monitor for useful information. 

Metrics can be of 2 types, singleton and instance. A singleton metric is just a single value of a particular type. with particular semantics and unit. An instance metric has specific instances with string names, each having a particular value, but all instances should have the same type, semantics and unit.

The metric names are of form `a.b.c.d` where the scope increases with each period. Typically the first identifier is the agent name itself, then a particular subsystem, then its particular property and so on.

The most commonly used and installed agent by default is the linux agent, exposing a bunch of filesystem, network and kernel related metrics like `network.tcp.maxconn`. The [vector](http://vectoross.io/) project uses some of these by default (see the default widgets created on http://vectoross.io/demo/, if you notice the url, you can see the metric names)

To see all agents that ship with PCP, see https://github.com/performancecopilot/pcp/tree/master/src/pmdas

PCP supports instrumentation through an especially configured agent called MMV, which monitors for memory mapped files in `PCP_TMP_DIR` and if the file is in a particular format, makes the metrics visible to PCP. The metric names begin with `mmv`, then an app name, and then a custom metric name, so `mmv.stringsvc.request.count`. The idea is that small client applications can expose metrics with minimum setup to PCP. The C API to implement instrumentation is bundled with PCP itself, while a Java API is implemented by a project called parfait, and now a golang API is implemented by speed.

The PCP daemon binds to port `44321`. This is the port that is used by different client tools like `pmval`, `pminfer` and so on... There is also a web daemon that binds to port `44323` that can take JSON encoded requests and is the one used by vector.

There are a couple of books, a [users and administrators guide](http://pcp.io/books/PCP_UAG/pdf/PCP-3-pcp-users-and-administrators-guide-en-US.pdf) to get familiar with the client tools, and a [programmers guide](http://pcp.io/books/PCP_PG/pdf/PCP-3-pcp-programmers-guide-en-US.pdf) to understand the agent and instrumentation API and possibly write your own agents.

Pinging @natoscott and @lberk in case I missed something

**Comment by peterbourgon** [comment]
Thanks to @suyash and his patient explanations on Slack, I have a pretty good understanding of how PCP works. Let me summarize, primarily for my own retrospective edification :)

Instrumented applications import the speed client, which typically opens a memory-mapped file that's shared by the PCP daemon. Metric observations are simple writes to that file, which are picked up by the daemon. An alternative write path involves connecting to the daemon and sending periodic JSON blobs.

The data model has two concepts. A singleton metric, which is a single set of label values and a concomitant value; most analagous to a Graphite dotted.notation.metric and value. And an instance metric, which is the same but parameterized in one dimension; for example, http.request.[get_foo,post_foo].count would be an instance metric with get_foo and post_foo _instances_.

So I think the closest thing to this would be package metrics/graphite. You'd have two constructors for your Reporter struct: one using the default memory-mapped file approach, currently called NewReporter, I suggest renaming to NewReporterMmap or something like this; and another POSTing JSON to an endpoint, maybe call it NewReporterHTTP or something. All metrics can treat With as a no-op, same as Graphite. And I think each _instance_ of an instance metric should be treated as its own Go kit metric. That is, http.request.get_foo.count is just a separate counter to http.request.post_foo.count. Hopefully this lines up with your thinking.

There are some problematic aspects to the speed client package re: global state and init functions, but since it's sequestered in metrics/pcp those problems are effectively opt-in and I'm fine with it.

So I'd be happy to accept a PR along those lines. I hope that's enough to go on; please feel free to ping me with any further questions! :)

**Comment by suyash** [comment]
@peterbourgon just a couple of things

- JSON over web daemon is an alternative for reading, not writing, for writing/reporting metrics there is only one interface, memory mapped files, for reading metric values there are multiple client tools that can send requests to the port the PCP daemon binds to (44321), while the web daemon (44323) is a separate program that can report metric values through JSON requests, but **not update them**

> There are some problematic aspects to the speed client package re: global state and init functions, but since it's sequestered in metrics/pcp those problems are effectively opt-in and I'm fine with it.

- I may be wrong about this but from what I see, except for the global erase file flag (https://godoc.org/github.com/performancecopilot/speed#pkg-variables) that if true will erase the memory mapped file on unmapping, I don't think there is any global state. Although if that is bad design, I can make it a property to set for each speed client, just like the MMV flag.

Once you are happy with the above points I would be happy to send a PR :)

**Comment by peterbourgon** [comment]
> JSON over web daemon is an alternative for reading, not writing . . .

Ah, OK! I'll update my comment above. That means you need only the one constructor.

> I don't think there is any global state . . .

Here's what I mean:

- https://github.com/performancecopilot/speed/blob/251682b/client.go#L37
- https://github.com/performancecopilot/speed/blob/251682b/config.go#L19
- https://github.com/performancecopilot/speed/blob/251682b/speed.go#L21

To pick one of those, the global logger is problematic because users may not want or be able to use the logrus package in their code. But, again, since this is only pulled in to a Go kit project if a user would import metrics/pcp, I'm basically OK with it.

**Comment by suyash** [comment]
closing this as #363 was merged
