### ISSUE TITLE
Should metrics expose their name?

### ISSUE THREAD

**Issue by elgris** [go-kit/kit#400]
For instance, constructor of `expvar.NewHistogram` receives a `name` as argument. Later, there is no way to get this `name` from created instance. `expvar.Histogram` hides its name in underlying private property `h   *generic.Histogram` which in its turn has `Name` as a public property.

I'm just wondering is there any sense to expose metrics' name through public method `Name`? First, I could use it for my own monitoring of created metrics. Second, it will remove inconsistency between, e.g., `generic.Histogram`  (exposes `Name`) and other kinds of histograms embedding generic one (and hiding `Name`).

If we agree to implement that, I can provide a pull request with changes.

**Comment by peterbourgon** [comment]
Package metrics is explicitly designed as a set of write-only interfaces. Hiding the name—or, rather, making it a property of the implementation's construction—is by design. Not all metrics have a single name! For example, expvar metrics are simple and parameterized exclusively on their name, but Prometheus metrics have potentially infinite label cardinality, all dimensions of which are required to uniquely describe the timeseries.

**Comment by peterbourgon** [comment]
Hopefully that answers the question, such as it was. Please re-open if you still have thoughts :)
