### ISSUE TITLE
log: default StdlibAdaptor timestamp and message keys shouldn't be terse

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#433]
"ts" and "msg" are great for debugging, but not great for standard field names. "timestamp" and "message" would be better, IMO.

Open to a PR?

**Comment by peterbourgon** [comment]
Nope. Brevity is more important than clarity here, at least for defaults.

**Comment by willfaught** [comment]
Why?

**Comment by peterbourgon** [comment]
Because log bloat is a real and growing ;) concern, and defaults are ubiquitous. If either ts or msg were at all ambiguous as log key names, I'd give pause... but they aren't. For something like this, where you're gonna see the keys on _every log line_ produced by your application, brevity is a virtue. IMO :)

**Comment by willfaught** [comment]
Not sure that I follow what you mean about defaults are ubiquitous. Do you mean the "ts" and "msg" defaults?

At a glance, could someone new to a system tell what the name ts means? It doesn't seem so to me: ts could be a collection of times, themes, tweets, or any number of problem domain-specific terms. My concern is that on-call engineers that need to investigate failures in unfamiliar systems need all the help they can get, and determining what ts might mean in a tool like Kibana is the last thing they need to worry about.

"When" seems clearer to me, and it's only 2 more chars.

What's the situation where log bloat is a problem? Is it running a service locally and reading the stdout/err directly? Surely most keys are much longer than 2 chars, so what's being saved in the long run if two keys are abbreviated? Most log content will be aggregated into logstash or something in production and not directly parsed by human eyes anyway, right?

That's all from a production-first perspective, I suppose, so if you're favoring development and debugging environments first, then that makes sense. I would think production-ready defaults would be preferable as a safe guard.

**Comment by basvanbeek** [comment]
Very much against changing a default. There are people already using Go kit in production and being perfectly fine with the established defaults. Changing them now only makes sense if a large majority of the community sees benefit. 

That said, any sane developer would layer and confiugure Go kit to feed it with the proper set-up that their platform needs. If you're not content with the current defaults you already have the opportunity to override the defaults by using `StdlibAdapterOption`'s and this adheres to Go-kit's common mantra of "be explicit" with configuration.

As a non native English speaker I might want / require different keys so we'll never be able to make everybody happy with a particular set of defaults and with the expense of pissing existing users off I'm perfectly fine with the argument of keeping the status quo which took brevity into account.

**Comment by peterbourgon** [comment]
I hear your arguments, @willfaught, I'm just not convinced that "ts" is ambiguous, or in any way "non-production-ready" for a key. But to reiterate @basvanbeek, if "ts" is ambiguous for you or your organization, then that's totally fine—you can create your StdlibAdapter with the TimestampKey("timestamp") functional option, and I think everyone is happy.

I'll close this now since it seems we're talking in circles. Thanks for the feedback! It keeps us honest :)

**Comment by willfaught** [comment]
OK, fair enough :)
