### ISSUE TITLE
log: StdlibAdaptor timestamp value is weird in logfmt format

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#434]
It's quoted and doesn't match the RFC3339 format of DefaultTimestamp/UTC:

```
timestamp=2017-01-11T12:58:52-08:00 caller=server.go:16 message=started
timestamp="2017/01/11 12:58:52.426762" caller=http.go:142 message="Serving [::]:8000 with pid 64404"
```

**Comment by peterbourgon** [comment]
That's the way the stdlib timestamp comes to us. As far as I can tell, changing it would involve parsing and reformatting as time.RFC3339[Nano]. I'm not sure that juice is worth the squeeze. Do you think?

**Comment by ChrisHines** [comment]
The quotes are required by logfmt because of the space in the value.

The date and time [formatting done by the stdlib log](https://golang.org/src/log/log.go#L90) package is hard coded and doesn't even use `time.Format`. We are already parsing in a fashion a regex. It may be possible to do a more thorough job and resolve this issue without loss of performance.

There is a workaround readily available, which is to turn off time recording on the stdlib log package and let the Go kit logger do that so that it is always consistent. See below.

```go
package main

import (
	"log"
	"os"

	kitlog "github.com/go-kit/kit/log"
)

func main() {
	logger := kitlog.NewLogfmtLogger(os.Stdout)
	logger = kitlog.NewContext(logger).With("ts", kitlog.DefaultTimestampUTC)

	slog := kitlog.NewStdlibAdapter(logger)

	log.SetFlags(log.Lshortfile)
	log.SetOutput(slog)

	log.Println("hello world")
}
```

Output:

```
ts=2017-01-12T00:03:54Z file=a.go:19 msg="hello world"
```

**Comment by willfaught** [comment]
@peterbourgon Ha, I've never heard that phrase before. :D

I was hoping it could be made uniform. It causes stutter in the terminal log output.

@ChrisHines Makes sense; forgot about the space.

Good idea about the workaround. I can use that.

**Comment by peterbourgon** [comment]
> We are already parsing in a fashion a regex. It may be possible to do a more thorough job and resolve this issue without loss of performance.

Good point. I'm open to this.

**Comment by peterbourgon** [comment]
I reckon this is finished now that #438 is merged.

**Comment by ChrisHines** [comment]
Yes, it is finished. But to clarify, #438 was closed without merging.
