### ISSUE TITLE
auth/jwt: Function names not intuitive.

### ISSUE THREAD

**Issue by ChrisHines** [go-kit/kit#526]
I've been using the auth/jwt package on a project for a while now and I constantly trip over the difference between `FromHTTPContext` and `ToHTTPContext`. The structure of the names don't help me remember which way the data is flowing.

From godoc:

----------

```go
func FromHTTPContext() http.RequestFunc
```
FromHTTPContext moves JWT token from context to request header. Particularly useful for clients.

```go
func ToHTTPContext() http.RequestFunc
```
ToHTTPContext moves JWT token from request header to context. Particularly useful for servers.

------------

I'd prefer the following renaming of these functions (and the corresponding gRPC pair):

`FromHTTPContext` -> `ContextToHTTP`
`ToHTTPContext` -> `HTTPToContext`

Do others find the current names confusing also?
Does anyone have better suggestions that mine?

**Comment by peterbourgon** [comment]
I have no objection, but I'd ask that we also audit the other similar-sounding function names in other packages, to have a uniform style.

**Comment by basvanbeek** [comment]
We have the following similar functions in Tracing:

ServerSide; pull data from header and push into Context:
`FromHTTPRequest` and `FromGRPCRequest`

ClientSide; pull data from Context and propagate in headers:
`ToHTTPRequest` and `ToGRPCRequest`

**Comment by willfaught** [comment]
Sounds confusing to me too.

**Comment by terinjokes** [comment]
I agree the terminology in`auth/jwt` is confusing, especially if you use the functions in the `tracing` package more often.

In tracing, you interpret the function names as "context to request" and "context from request", whereas in auth, you interpret it as "from http to context" and "to http from context".

Adapting the proposed names with the scheme used in tracing, how about:

* `RequestToContext`
* `ContextToRequest`

Since these functions will be called with the transport name directly to the left, we don't need to repeat ourselves.

**Comment by peterbourgon** [comment]
I believe this was fixed recently, is that true?
