### ISSUE TITLE
Support Pretty printed JSON w/ kitlog 

### ISSUE THREAD

**Issue by foklepoint** [go-kit/kit#552]
Can we have an option to pretty print JSON with JSON Logger? We're using the go's native JSON encoder which has built in option to do this. I can prepare up a PR to add an option for this functionality if we are interested in supporting it.

**Comment by ChrisHines** [comment]
I think the use case needs to be pretty persuasive here.

My first concern is that it would require the JSON encoder used by the log package to support the concept of pretty printing. I would like to keep the door open to using a faster JSON encoder tuned to the logging use cases as I experimented with in the json-log branch. That proof of concept demonstrated significant performance gains. I'm not sure that an optimized encoder will benefit from including pretty printing logic

A secondary concern is that neither of the two built in log formats currently have any options other than the `io.Writer` they output data to. This has the advantage that the "constructors" for both have the same function signature (`func(io.Writer) Logger`), which I like because it allows them to be passed directly to functions in the `log/term` package.

Can you explain the setting in which you would like an application to pretty print its logs?

**Comment by foklepoint** [comment]
My use-case was during debug/development, I want devs to look at the nicely formatted JSON outputted by the logger. It would make sense to not support this upstream in go-kit if there isn't a whole lot of interest.

**Comment by ChrisHines** [comment]
In the debug/dev environment I would be inclined to pipe the output through another tool that does the pretty printing after the fact. I do that all the time when inspecting web API results coming back from `curl`. See, for example: https://lornajane.net/posts/2013/pretty-printing-json-with-pythons-json-tool.

**Comment by foklepoint** [comment]
That's something I'm already doing. It just yet another dependency you need to be able to run an opinionated dev setup locally

**Comment by yurishkuro** [comment]
The zap logging library just provides a plain text log encoder when in development. It writes logs as k=v space separated sequence, which is fairly readable. I personally prefer logs in one line, much easier to grep than pretty printed JSON.

**Comment by foklepoint** [comment]
I believe this can be closed. Doesn't seem like there is a lot of interests and the work-arounds mentioned are good enough
