### ISSUE TITLE
WriteTo() resets Counter but it doesn't reset Histograms

### ISSUE THREAD

**Issue by AlexAkulov** [go-kit/kit#553]
Hello! 
I use kit/metrics/graphite library for sending stats every minute. Values of Counters are reset after I call WriteTo() method and it is correct. But values of Histograms accumulate data from the start of the program and they don't reset values after calling WriteTo(). I think it is wrong. Usually it's not necessary to know what values of the percentiles from the start program are, I have to know what values of the percentiles were for every minute.

I think that WriteTo() has to reset histograms too.

**Comment by peterbourgon** [comment]
Histograms in the program memory space collect observations (i.e. raw data); histograms as emitted to a backend like Graphite are already statistical summaries of those observations (i.e. not raw data). The underlying implementation (in our case, vividcortex/gohistogram) [takes care of managing](https://github.com/VividCortex/gohistogram/blob/master/numerichistogram.go#L114) the cardinality of observation buckets; sometimes based on a moving time window, sometimes based on pure number of observations (as is the case here).

So I think you've got the wrong concept for what a histogram is. It's more like a gauge than a counter: it's got some state built in to its emissions, with hysteresis. In short, IMO, we shouldn't be resetting state. And this is a good thing, because the vividcortex implementation has no mechanism for doing that, anyway ;) 

But thanks for the discussion! I learned a few things doing the research.
