### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by andrey-moor** [go-kit/kit#636]
Is there any way to use the kit with GraphQL?

**Comment by nicolaiskogheim** [comment]
I use go-kit with [graphql-go/graphql](https://github.com/graphql-go/graphql) and [granateio/granate](https://github.com/granateio/granate/) at work. Granate is by a colleague of mine, which is why we can use it despite big "WORK IN PROGRESS" message 😄 .

I initially got inspiration from [narqo/test-graphql](https://github.com/narqo/test-graphql) and then created a test project at [nicolaiskogheim/go-kit-graphql-todo](https://github.com/nicolaiskogheim/go-kit-graphql-todo/) (let me know if that one's useful, and then I can update it to how I would've done things now). narqo does it without granate, and I do it with granate, both use go-kit and GraphQL.

**Comment by nicolaiskogheim** [comment]
To outline the idea briefly: You have a GraphQL service with one http endpoint where all GraphQL requests go. GraphQL now becomes its own layer, sitting between transport and services. The GraphQL service uses service methods on your other services, so the GraphQL service needs to be constructed with those services.

**Comment by peterbourgon** [comment]
@andrey-moor Does that help answer your question?

**Comment by andrey-moor** [comment]
Yeah that's enough for now, thx @nicolaiskogheim

**Comment by sagikazarmark** [comment]
Here is another example using [gqlgen](https://gqlgen.com).

https://github.com/sagikazarmark/modern-go-application/pull/81
