### ISSUE TITLE
How to use the Shipping example?

### ISSUE THREAD

**Issue by ruudk** [go-kit/kit#642]
The README doesn't explain how to use the Shipping example.

**Comment by peterbourgon** [comment]
I don't understand what you mean by "how to use". Can you say what you're having trouble with?

**Comment by ruudk** [comment]
I see. I saw a talk of you at a conference, so I checked out the website, clicked examples, clicked the most interesting example, and tried to run it so see what it would do, so that I can check the code accordingly. For me, that's a good way to learn new stuff. I'm very new to Go, coming from PHP.

So if the readme would contain something like: 
* execute `go run main.go`
* issue a post to /v1/...
* call the cargo list with GET /v1/....

that would help ;)

**Comment by peterbourgon** [comment]
Well, Go kit certainly assumes a base level of familiarity with how to build and run Go programs. In this case,

```
$ go get github.com/go-kit/kit/examples/shipping
$ shipping -h
```

should get you started. A README section detailing a set of example HTTP queries to exercise the components is probably out-of-scope, but I'd be happy to take a PR, if anyone felt so inclined.

**Comment by hiferoz** [comment]
An explanation like below example would have been great. 
[https://gokit.io/examples/stringsvc.html#stringsvc3](url)

There are quite a few real-world like examples but none have any proper explanation or documentation. If you are kind enough to do so, it would be such a treasure for people like me :)

Or at-least provide some curl commands in the README file, so that once we get the shipping example up and running, we can try it out to understand it better then use debugging to walk through the various parts of code. I hope you understand the point I am trying to make...
