### ISSUE TITLE
Support for tags and fields in opentracing middleware

### ISSUE THREAD

**Issue by peppelan** [go-kit/kit#653]
When GoKit's middleware creates opentracing spans, the current implementation lets the user specify what is the span name (`operationName`).

In this context, opentracing also allows for attaching `tag`s and `field`s to a span.
It would be nice if GoKit's middleware could allow for these to be set.

For example, the GoKit's middleware could accept - at creation time - optionally a `SpanTagger` and a `SpanFieldLogger` interface that when provided would finally be asked for the set of tags & fields to be attached to the to-be-created span for a given request.

**Comment by basvanbeek** [comment]
I can see where a limited amount of default Tags might make sense for adding context to spans originating from a service, but Loggers should be dealt with very carefully. These typically are used to annotate timed events / exceptions occurring during the lifetime of a span and typically don't happen automatically right at span creation time. (if so they are tied to the start of the span or the span in general and would be better suited being just tags).

**Comment by peppelan** [comment]
@basvanbeek I am OK to remove field logging from the scope of the issue, since the implementation that I want to replace only attaches tags.

This said, do you see the remaining part of this issue as something that could potentially be accepted as contribution to GoKit?
Thanks,
Peppe

**Comment by basvanbeek** [comment]
Which tracing backend are you using?

**Comment by peppelan** [comment]
Zipkin

**Comment by basvanbeek** [comment]
If using Zipkin you might want to check out the following middleware code for Go kit, which is currently under development. 

https://github.com/basvanbeek/kit/pull/2

I still need to add unit tests and improve documentation before sending a PR to Go kit for this, but it uses the native Zipkin tracer implementation zipkin-go instead of zipkin-go-opentracing. It is much cleaner and more Zipkin idiomatic.

**Comment by peppelan** [comment]
I saw the change, and a couple things come to my mind:
- not 100% sure I would onboard the change as using the standardised connector would more easily allow for swapping the backend in case of need
- getting back to the issue, it seems that also the code you are working on might miss the ability to attach tags at span creation (tags seem to be pre-provided at middleware creation, except for URL and method)

**Comment by basvanbeek** [comment]
1) I disagree here as Go kit is used typically at the API end consumer level (devs building micro services). A native tracer has far less issues for people in polyglot environments and switching between backends is almost never as easy as configuration. This will only work in greenfield environments and taking extra precautions to only use the far too wide OT API in a way that its supported by the tracers you think changing between.

2) you mean you want to decide what needs to be tagged on a per request basis (depending on request input)? That warrants its own endpoint middleware as that is highly personalized. No need to clutter the standard api... you can always fetch the span from context and add both tags and logs.

**Comment by peppelan** [comment]
Hi, thanks for your answers. 

"2." is indeed the point of this issue, and my intention is to provide extensibility to the standard implementation that would allow more people (including me) to use it rater than implementing their own middleware.

As an example I stepped recently on, GoKit does provide [DefaultErrorEncoder](https://github.com/go-kit/kit/blob/master/transport/http/server.go), but at the same time it allows you to plug your own logic by the `Headerer` and `StatusCoder` interfaces.

Anyways, this issue is for getting a feedback on the proposal, and if in this context such extensibility is seen as clutter, well, that is a feedback 😄

**Comment by basvanbeek** [comment]
For what you want to do we already have the ServerBefore functions... you'd just plug your ServerBefore RequestFuncs to be hit after the opentracing HTTPToContext has been done...

example:
```go
tagHandler := func(ctx context.Context, req *http.Request) context.Context {
    if span := opentracing.SpanFromContext(ctx); span != nil {
        span.SetTag("request-id", req.Header.Get("X-Request-Id"))
    }
}
```

**Comment by yurishkuro** [comment]
> I disagree here as Go kit is used typically at the API end consumer level (devs building micro services). 

While the argument above might work if the service is **only** using one single RPC framework, in which case the exact tracing integration is mostly invisible to the app developer, that is not generally the case, as the services are also using db connections, possibly other RPC frameworks / native clients, etc., etc. And suddenly we're talking not just about instrumenting a single library but a large ecosystem. Having a standard API to instrument that ecosystem and the ability to **share instrumentation** across all tracing implementations is what OpenTracing provides. 

> A native tracer has far less issues for people in polyglot environments and switching between backends is almost never as easy as configuration. This will only work in greenfield environments and taking extra precautions to only use the far too wide OT API in a way that its supported by the tracers you think changing between.

There's nothing "non-native" about, say, Jaeger tracers, or a dozen of traces from commercial vendors that are OpenTracing compatible, and they work perfectly fine in polyglot environments. Incidentally, Jaeger tracers used to be implemented as 100% Zipkin compatible in the past with no issues. And the difficulty of swapping tracer implementation is not the side effect of any tracing API but of microservices in general (the problem of lock step release).

**Comment by adriancole** [comment]
@yurishkuro you are directly misleading people. There are not dozens of vendors. If so, please cite their tracer implementations? Also, there are definitely proprietary extensions (ex lightbend, and anything related to a sampling). You failed to mention there's no test for one to know if any of the implementations that do exist can swap, rather just leave it to conjecture. Finally, the versions of opentracing imply technically difficult compatibility challenges at the bottom of the stack. If you want to make this issue (yet another) misleading road to difficulty for those who trust blindly, so far so good. However, if OT is so great you could possibly be able to suggest some challenges people will have and that eventhough there are challenges they are better off for it.

**Comment by yurishkuro** [comment]
I did not say "dozens", but "a dozen". Instana, DataDog, SolarWinds/TraceView, NewRelic, Lightstep, InspectIT - that's half a dozen who already support OT, and there are others who said they will. There are also open source systems, like Zipkin, SkyWalking, Jaeger, Stagemonitor. This is `>>1` backend one will be able to use with the same instrumentation.

There have been a number of talks at conferences showing how the same application can be traced with different tracing backends, just by using a different tracer implementation. Some features may work better than others in different implementations - after all a common API can only provide a lowest common denominator. But one still gets like 80% of the basic tracing functionality via OpenTracing instrumentation after swapping tracers. 

That's not to mention that swapping the tracers in a deployed environment isn't even the ultimate goal. The goal is to be able to share instrumentations instead of redoing them for every tracer implementation. The go-kit is a perfect example here. go-kit is "tracing enabled", but if it was instrumented with a bespoke api of implementation X, it wouldn't be "tracing enabled", it would be "tracing with X and only X enabled". If your company decided to use Y, then you out of luck, you have to do it yourself.

Nothing is perfect, OpenTracing is evolving, some changes are more painful than others. But to say that one is better off by sinking months of engineering time into instrumenting a system with a bespoke api of X, rather than using an API that lets you choose X or Y or Z later, that is misleading.

**Comment by peppelan** [comment]
Whether opentracing's generic or any other specific connector should be used was a side comment where we shared different views, but this thread is not about it.

I got from @basvanbeek a suggestion on how to plug tags/log entries while still using GoKit's tracing middleware, so I think this comment resolves the issue. I will therefore close this issue and encourage you to follow up with the open discussion in a more appropriate place if you wish to.

Thank you all for participating.
Peppe
