### ISSUE TITLE
Issue with go-kit while building

### ISSUE THREAD

**Issue by continuum-koustubh-kulkarni** [go-kit/kit#658]
Our  project is  currently using  github.com/go-kit/kit and version e3b2152e0063c5f05efea89ecbe297852af2a92d.

Whe we are building with make we are getting below error 
no buildable Go source files in /{projectGoPath}/{Project}/src/vendor/github.com/go-stack/stack

It seems go-kit  referring to go-stack latest version and that is causing such problem.Is this the case? Please suggest

**Comment by nicolaiskogheim** [comment]
I don't get this error. How do you build?

**Comment by continuum-koustubh-kulkarni** [comment]
we are on ubunto and use make file to build project which executes  go build
 command. This results the error about no buildable for go-stack

**Comment by nicolaiskogheim** [comment]
I'm sorry, I wasn't clear. How does your `go build` command look?

**Comment by ChrisHines** [comment]
Yes, github.com/go-kit/kit/log depends on github.com/go-stack/stack. I am also the author and maintainer of go-stack. It is a stable project with tagged releases.

Without more information I have two guesses as to why you get the "no buildable Go source files" error.

1. The go-stack project is not properly vendored, meaning that the source files did not get properly copied into /{projectGoPath}/{Project}/src/vendor/github.com/go-stack/stack.

2. You are using an old version of Go. As documented on the go-stack [releases page](https://github.com/go-stack/stack/releases), go-stack v1.7.0 works with Go version 1.7 or newer. If you want a version of go-stack that works with an earlier version of Go, then you should pin to go-stack v1.6.0.

Since you mentioned that you are using Ubuntu, I suspect that you are using an old version of Go. I have heard that the Ubuntu apt-get repos ship an old version of Go, especially if you are on an older version of Ubuntu. You can find out what version of Go you have with the command `go version`. If it turns out that you do have an old version of Go then you have two choices, either install and start using the newest version of Go (highly recommended), or use go-stack v1.6.0.

**Comment by continuum-koustubh-kulkarni** [comment]
Thanks a by upgrading to new go version ,it worked.

**Comment by continuum-koustubh-kulkarni** [comment]
Thanks a by upgrading to new go version ,it worked.
