### ISSUE TITLE
Please provide full example of how to do logging to file instead of standard input /output also including how to specify log rotation on log files .

### ISSUE THREAD

**Issue by sohimankotia** [go-kit/kit#701]

**Comment by fredipevcin** [comment]
I would suggest [opening a file](https://golang.org/pkg/os/#OpenFile) and pass this to `log.NewSyncWriter`

Example:
```go
logger := log.NewLogfmtLogger(log.NewSyncWriter(file))
logger.Log("msg", "starting")
```

Searching for log rotation first hit on Google is https://stackoverflow.com/questions/28796021/how-can-i-log-in-golang-to-a-file-with-log-rotation or use some other. Maybe it would be better to use https://linux.die.net/man/8/logrotate.

Next time try to ask on [slack](https://github.com/go-kit/kit#go-kit------) instead of opening an issue.

**Comment by peterbourgon** [comment]
Beyond what @fredipevcin has explained, it's worth nothing that your Go kit microservice should almost certainly not be writing log files to disk, nor managing log file rotation. That is typically the job of another process, e.g.

```
myservice 2>&1 | svlogd
```

**Comment by sohimankotia** [comment]
Thanks a lot .
