### ISSUE TITLE
The usage of context in Valuer in the logger

### ISSUE THREAD

**Issue by izaurio** [go-kit/kit#716]
Question about the possibility to use context in the calculation of the Valuer function.
An example of the composition of the program below.
We can make a logger that will calculate the coller at the time of recording.
But if we form a request id value for each http call. Then, in the absence of a direct logger transmission, we cannot do a Valuer calculation based on the context value. 
Inside the function `(s Store) Create`, we have to extract the request id value from the context by hands.

Is there exists workaround for doing it?

```
package main

import (
	"context"
	"database/sql"
	"net/http"
	"os"
	"time"

	"github.com/go-kit/kit/log"
	"github.com/satori/go.uuid"
)

func main() {
	logger := log.NewJSONLogger(os.Stdout)
	logger = log.With(logger, "ts", log.DefaultTimestampUTC, "caller", log.DefaultCaller)

	store := Store{Logger: logger}
	bm := BookMarket{Store: store}

	mux := http.NewServeMux()
	mux.Handle("/", handler(&bm))
	http.ListenAndServe(":8080", mux)
}

func handler(bm *BookMarket) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reqID := uuid.NewV4().String()
		ctx := context.WithValue(r.Context(), "request_id", reqID)
		// logger = log.With(logger, "request_id", reqID)
		bm.CreateBook(ctx, r.URL.Path)
		w.WriteHeader(http.StatusCreated)
	})
}

type BookMarket struct {
	Store DataStore
}

func (bs *BookMarket) CreateBook(ctx context.Context, title string) error {

	bs.Store.Create(ctx, title, time.Now())
	return nil
}

type DataStore interface {
	Create(ctx context.Context, title string, createdAt time.Time)
}

type Store struct {
	DB     *sql.DB
	Logger log.Logger
}

func (s Store) Create(ctx context.Context, title string, createdAt time.Time) {
	s.Logger.Log("query", "INSERT", "title", title, "created_at", createdAt)
	// manual passign request id from ctx
}

```

**Comment by ChrisHines** [comment]
Consider a helper function like:

```go
func RequestIDLogger(ctx context.Context, logger log.Logger) log.Logger {
    return log.With(logger, "request_id", RequestIDFromContext(ctx)
}
```

**Comment by izaurio** [comment]
Any chance of getting behaviour like that?
```go
// log
type CtxValuer func(context.Context) interface{}

// custom package
func RequestID() Valuer {
	return func(ctx context.Context) interface{} { return RequestIDFromContext(ctx) }
}

// main func
logger := log.NewJSONLogger(os.Stdout)
logger = log.With("request_id", RequestID())

// custom package
func (s Store) Create(ctx context.Context, ...) {
	s.Logger.LogCtx(ctx, "query", "INSERT", ...)
}
```

Where logger receives the context and passes it to Valuer func?

Helper is good, thank you. But why can we not use the context in Valuer function?

**Comment by ChrisHines** [comment]
I don't think that's a good pattern.

The logger created in the main function should only store key/value pairs that will be emitted with every log event for the entire life of the program. It shouldn't be concerned with request data until it's inside a request handler.

> `s.Logger.LogCtx(ctx, "query", "INSERT", ...)`

This looks like a suggestion to add a `LogCtx` method to the `log.Logger` interface. That would be a breaking change that we're not going to do in the go-kit log package in the foreseeable future. The  `log.Logger` interface is frozen.

If you want `Store.Create` to log request scoped data I think you have several choices:

1. Extract the request data from the context within `Store.Create`. That requires `Store` to know what request data to look for. I wouldn't do this, as `Store` should be useful either in or outside of any request scope.
2. Have a generic way of storing request based key/value pairs in a context and getting them back later. Example here: https://github.com/peterbourgon/breakfast-solutions/blob/master/logging.go#L107
3. Change the method signature to `Store.Create(ctx context.Context, logger log.Logger, title string, createdAt time.Time)` and pass in a logger with the request key/value pairs already populated.
4. Put a request scoped `log.Logger` in the context, which is similar to 2 above, but uses the logger to hold the request data instead of a separate container type.

**Comment by izaurio** [comment]
> It shouldn't be concerned with request data until it's inside a request handler.

It's a clear.

Changing the signature to `Store.Create(ctx context.Context, logger log.Logger, ...)`  will change the caller signature if it did not have a logger. 

We consider that exceptional case when the logger is needed inside `store.Create`. If the logger is not needed inside, the problem can be solved with the wrapper. https://github.com/go-kit/kit/blob/1b1a55c53e898557056c7f3fe05be3760a48f172/examples/addsvc/pkg/addservice/middleware.go#L15

Since the wrapper will be with high probability, method 2 and 4 can implement the described scenario.

**Comment by exfly** [comment]
Tried to fork a copy and added my own method
https://github.com/go-kit/log/pull/23
