### ISSUE TITLE
Pass data between service and transport (espcially ServerAfter)

### ISSUE THREAD

**Issue by ddeep2007** [go-kit/kit#718]
I am fairly new to go and have been using go-kit for the past couple of weeks and have found it to be a great toolkit. One issue I am facing though is the need to pass data from my business logic (service) back to the transport? For example based on certain operations in my business logic I want to set a cookie with user data as part of my http response in my transport. At present I am creating the cookie in the ServerAfter method but there is no way for me to access data provided by the service to populate it. Am I missing something very basic?

**Comment by peterbourgon** [comment]
I think your best option is to modify the response type to include transport-specific information, like the cookie value. Your EncodeResponseFunc can then extract that information from the response type and do specific things to the e.g. http.ResponseWriter.

**Comment by ddeep2007** [comment]
Makes sense. Thanks!!

**Comment by peterbourgon** [comment]
In a transport/http.Server, it's already possible to take information from the http.Request and feed it into the context before the business logic, via [RequestFunc](https://godoc.org/github.com/go-kit/kit/transport/http#RequestFunc)); and to take information from the context and http.ResponseWriter and (optionally) feed it into the context after the business logic, via [ServerResponseFunc](https://godoc.org/github.com/go-kit/kit/transport/http#ServerResponseFunc). 

I think these are the only _really_ legitimate uses of context in a request flow, and I'd resist wiring it up anywhere else. I'm trying to avoid situations where the context becomes a generic or default way of moving information around, because it's not type safe, it's opaque, it can obscure intent, and it makes maintaining code more difficult. [See here for more rationale](http://peter.bourgon.org/go-for-industrial-programming/#context-use-and-misuse).
