### ISSUE TITLE
Its not easy to make a stateful endpoint

### ISSUE THREAD

**Issue by MaruHyl** [go-kit/kit#875]
For example, let some special request choice a special endpoint, not random or round-robin

**Comment by MaruHyl** [comment]
If `kit` can have an ContextBalancer, things will be simpler
```
type Balancer interface {
	Endpoint() (endpoint.Endpoint, error)
}

type ContextBalancer interface {
	Endpoint(ctx context.Context) (endpoint.Endpoint, error)
}
```
In Retry
```
...
if cb, ok := b.(ContextBalancer); ok {
    e, err = cb.Endpoint(ctx)
}else{
    e, err = b.Endpoint()
}
...
```

**Comment by basvanbeek** [comment]
And how would you distinguish a special endpoint? 

If this issue is about traffic steering between a v1 and v2 of a service I would typically have both in two different load balancer sets (so in a load balancer I have identical service instances). 
Then in the service glue code for the endpoint I would add my logic to choose from which load balancer set I would request a service instance.

If this is about instance stickyness you can also solve this outside the load balancer itself.

Do you have a more concrete example on when you would use this? Right now I'm missing a real rationale on why this is the right solution to your undisclosed problem.
