### ISSUE TITLE
Does go-kit provide  client connection pool?

### ISSUE THREAD

**Issue by tangleiao** [go-kit/kit#931]
Dose go-kit provide  client connection pool? such as robbion using okhtttp's pool in spring cloud

**Comment by ChrisHines** [comment]
Go kit does not provide a client connection pool because that is handled by other packages in the Go ecosystem. For example, the Go standard library [`net/http`](https://golang.org/pkg/net/http) package provides client connection pooling via [`http.Client`](https://golang.org/pkg/net/http/#Client) which by default uses a [`http.Transport`](https://golang.org/pkg/net/http/#Transport) connection pool to get connections.

I do not have any hands on experience with OkHttp, but from reading the [high level description](https://square.github.io/okhttp/) it seems to me that the Go `net/http` package fills the same role as OkHttp.

**Comment by tangleiao** [comment]
Ok， thank you， if grpc client or thrift client， can you give some suggestion？

**Comment by ChrisHines** [comment]
I believe both of those protocols will benefit from the same connection pooling provided by the Go standard library.

**Comment by tangleiao** [comment]
Can you tell me a open source project that is developed with go-kit?

**Comment by ChrisHines** [comment]
> Can you tell me a open source project that is developed with go-kit?

Since you asked in the context of client connection pooling, maybe one of the links in the godoc list of [packages that import `github.com/go-kit/kit/transport/http`](https://godoc.org/github.com/go-kit/kit/transport/http?importers) will help you find what you are looking for.

Looking through that list, this project that uses Go kit looked interesting https://github.com/golangci/golangci-api.
