### ISSUE TITLE
Allow server RequestFunc() to return error

### ISSUE THREAD

**Issue by drscre** [go-kit/kit#938]
I want to create a ServerBefore() option which adds full http request body to context in order to log it later to simplify debug.
For this, i need to read request body into buffer. But i am not sure how to properly handle error  in this case.

```golang
func withHttpBody(ctx context.Context, r *http.Request) context.Context {
        b, err := ioutil.ReadAll(r.Body)
	if err != nil {
		// How to handle error here? 
	}
	r.Body = ioutil.NopCloser(bytes.NewBuffer(b))
	ctx = context.WithValue(ctx, "http_request_body", b)
	return ctx
}
```

**Comment by basvanbeek** [comment]
Why not log the error and have the context value be non existent / empty. Or if you dump the context value without much parsing in the log you could just insert the error details to simplify debugging in case of a body read issue.

**Comment by drscre** [comment]
If there is an error while reading request body there is no point to process it futher. Decoding will fail anyway.

**Comment by basvanbeek** [comment]
That is not the concern of ServerBefore which is inspection only. If you'd allow to error out here you basically change behavior of your service based on a server before middleware being there or not. It's really best to keep it in the single location which has the concern of decoding the request and handling errors if decoding fails. Decoding error handling belongs in the DecodeRequestFunc logic which happens shortly after.

**Comment by drscre** [comment]
It looks i have to pass decode error via context...
```golang
func withHttpBody(ctx context.Context, r *http.Request) context.Context {
	b, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return context.WithValue(ctx, "decode_err",err)
	}
	ctx = context.WithValue(ctx, "http_request_body", b)
	return ctx
}
```

and check for it in request decoder
```golang
func decodeRequest(ctx context.Context, r *http.Request) (interface{}, error) {
	if decodeErr, ok := ctx.Value("decode_err").(error); ok {
		return nil, decodeErr
	}
        ...
}
```

**Comment by peterbourgon** [comment]
The BeforeFunc was designed without an error return precisely to discourage users from doing things like this :) Reading the entire request body into memory opens you up to a lot of attack vectors and performance problems, and doing it on every request wastes CPU and RAM. The only situation where I'd do this is in a debug/troubleshooting context, and in that case, I guess what you're doing now is fine enough. 

All that said, I would personally just ignore the ioutil.ReadAll error, because the situations where it will fail would almost certainly cause different errors in the request path that you'd notice before this one.
