### ISSUE TITLE
Question about tracing & log

### ISSUE THREAD

**Issue by masihtehrani** [go-kit/kit#958]
Hi guys
I'm new to join Go-kit. We use in Fin-tech project.
I have some questions about tracing & log.
We used example Addsvc to complete our Projects.
1. in example Addsvc exist native Zipkin and Zipkin with Opentracing When running with native Zipkin all request add with depth and span 2 and when running with Opentracing just have 1 span & depth. Why? and we use tracing and log in our project with some level logic and we have database but our code has the same behavior example and just have 1 depth
2. We wanna trace and debug our code on the run level. and we need to add log in tracing how can integrate trace and log?
3. Could you please complete Addsrv example with best practice log, trace & monitoring

**Comment by basvanbeek** [comment]
Due to time constraints I will answer briefly. If more detail needed and there is a bug in the example code it might take some time before I can get to it.

1. Zipkin uses a concept of RPC spans which means client side and server side of an RPC share a span. This is a setable configuration defaulting to true. Most other tracers have a span per node so client and server each create their own and the server side span is a child to the client side span. In OpenTracing documentation at the time the single span per node was often communicated. When I wrote the first Zipkin tracer implementation for OpenTracing I defaulted it to span per node. This can make you see different span depths. As said they are configurable (the Zipkin opentracing implementation has now been turned into a wrapper of the native implementation). This also means that Zipkin users are adviced to use the Native tracer as it is more performant and idiomatic to Zipkin.

2. Trace and log integration is typically done by correlation. Remember that the decision factor semantics for incudling events into a trace or a log are different. A trace typically is sampled while a logline is typically recorded based on set severity level. So typically you create a correlation id (request id) and propagate it through in process context and out of process rpc headers. Example of correlation id can be found in one of the tests. You'd record the correlation id in the root span (you can record in others but will have low value as your search responses are on trace granulatity, not span granularity) and you'd record it in all log lines (so you can stitch log lines dealing with the request together as well as tie it to the corresponding trace). Stuffing logs in tracing ecosystems is a bad idea as you'd need to either implement 100% tracing or tail based sampling, both of which are quite expensive in a high QPS system.

3. It is better served with a separate example solely focussing on a single tracing technology and how to instrument microservices. AddSvc is a grab all highlighting most features of Go kit including multiple tracing ecosystems and therefore not that great to isolate a particular concern for best practices.

**Comment by masihtehrani** [comment]
> Due to time constraints I will answer briefly. If more detail needed and there is a bug in the example code it might take some time before I can get to it.
> 
> 1. Zipkin uses a concept of RPC spans which means client side and server side of an RPC share a span. This is a setable configuration defaulting to true. Most other tracers have a span per node so client and server each create their own and the server side span is a child to the client side span. In OpenTracing documentation at the time the single span per node was often communicated. When I wrote the first Zipkin tracer implementation for OpenTracing I defaulted it to span per node. This can make you see different span depths. As said they are configurable (the Zipkin opentracing implementation has now been turned into a wrapper of the native implementation). This also means that Zipkin users are adviced to use the Native tracer as it is more performant and idiomatic to Zipkin.
> 2. Trace and log integration is typically done by correlation. Remember that the decision factor semantics for incudling events into a trace or a log are different. A trace typically is sampled while a logline is typically recorded based on set severity level. So typically you create a correlation id (request id) and propagate it through in process context and out of process rpc headers. Example of correlation id can be found in one of the tests. You'd record the correlation id in the root span (you can record in others but will have low value as your search responses are on trace granulatity, not span granularity) and you'd record it in all log lines (so you can stitch log lines dealing with the request together as well as tie it to the corresponding trace). Stuffing logs in tracing ecosystems is a bad idea as you'd need to either implement 100% tracing or tail based sampling, both of which are quite expensive in a high QPS system.
> 3. It is better served with a separate example solely focussing on a single tracing technology and how to instrument microservices. AddSvc is a grab all highlighting most features of Go kit including multiple tracing ecosystems and therefore not that great to isolate a particular concern for best practices.

Thanks @basvanbeek your explanation was great. I didn't find good example code in go-kit for tracing and log, it's not important it's developed with several tools such as Zipkin, Jaeger, Opentracing & ... it's just developed for one thing but it's complete
