### ISSUE TITLE
Enhancement: log.WithSuffix

### ISSUE THREAD

**Issue by vinayvinay** [go-kit/kit#991]
Contrary to [`log.WithPrefix`](https://godoc.org/github.com/go-kit/kit/log#WithPrefix), which prepends keyvals to those passed to `Log`, we have a requirement to _append_ keyvals.

Especially if a human is reading logfmt output on the shell or in the web browser, it helps to have certain fields prefixed, e.g. `ts`, but certain fields are better when suffixed, e.g. `caller`, `environment`, so that more important information appears first, e.g.:

```
// WithPrefix: ts, caller, service, environment
// Log: event
ts=2020-06-12T13:20:52.417486636Z caller=run.go:217 service=push-service environment=staging event=step.started
```

could be better `WithSuffix`:
```
// WithPrefix: ts
// WithSuffix: caller, service, environment
// Log: event
ts=2020-06-12T13:20:52.417486636Z event=step.started caller=run.go:217 service=push-service environment=staging
```

Here's what [it might look like in code](https://github.com/go-kit/kit/commit/3067c4ab6964fde6f73aec0bdd7a89fe38e01173), which is just a draft, will polish it up and PR if there's interest. Do you think `WithSuffix` will come handy?

**Comment by vinayvinay** [comment]
Hello @peterbourgon @ChrisHines, do you have any thoughts on this one?

**Comment by peterbourgon** [comment]
I don't have strong opinions, but I'm not immediately convinced that this is useful enough to justify the complexity. I'm also a little concerned there might be a performance impact. Could you add a few test cases so I can see the behavior? Mixing and matching `log.WithPrefix`, `log.WithSuffix`, and `log.With`.

**Comment by peterbourgon** [comment]
Another reason this is of indeterminate value is that not all output formats respect order (e.g. JSON).

**Comment by ChrisHines** [comment]
My apologies for the late response.

My first reaction when I saw this feature request was skepticism. After a little thinking about what the implementation might look like I was less concerned  because in my mind it looked pretty much like what you wrote in your prototype and it doesn't feel too costly. I would like to see some benchmarks but it seems like it shouldn't add much overhead for people that never use it.

My biggest concern at this point is whether it pays for the cost of an additional exported function in the API. It may, since I cannot think of a good way to implement it externally and get semantics similar to to `With` and `WithPrefix`.

My vote is to proceed with a PR and benchmarking.

**Comment by vinayvinay** [comment]
Thank you for these inputs, fair points. I will come back with a PR with benchmarks.
